### ISSUE TITLE
Fails to compile on Ubuntu 64bit machine

### ISSUE THREAD

**Issue by oddtazz** [simmel/saslxoauth#1]
Output for /etc/lsb-release :-
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.10
DISTRIB_CODENAME=quantal
DISTRIB_DESCRIPTION="Ubuntu 12.10"

Output for uname -a :-
Linux gaurav 3.5.0-27-generic #46-Ubuntu SMP Mon Mar 25 19:58:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

libsasl2-dev version =  2.1.25.dfsg1-5
liboauth-dev version = 0.9.7-0ubuntu1 

Output of "make" :- 
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -DHAVE_CONFIG_H -I. -O2 -c xoauth.c -fPIC -DPIC -o xoauth.lo
(cd . && ln -fs xoauth.lo xoauth.o)
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -DHAVE_CONFIG_H -I. -O2 -c xoauth_init.c -fPIC -DPIC -o xoauth_init.lo
(cd . && ln -fs xoauth_init.lo xoauth_init.o)
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -DHAVE_CONFIG_H -I. -O2 -c plugin_common.c -fPIC -DPIC -o plugin_common.lo
plugin_common.c: In function ‘sockaddr_unmapped’:
plugin_common.c:98:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
plugin_common.c: In function ‘_plug_get_simple’:
plugin_common.c:347:5: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [enabled by default]
plugin_common.c:347:5: note: expected ‘int (**)(void)’ but argument is of type ‘int (**)(void _, int,  const char *_, unsigned int _)’
plugin_common.c: In function ‘_plug_get_password’:
plugin_common.c:409:9: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [enabled by default]
plugin_common.c:409:9: note: expected ‘int (__)(void)’ but argument is of type ‘int (__)(struct sasl_conn_t *, void *, int,  struct sasl_secret_t *_)’
plugin_common.c: In function ‘_plug_challenge_prompt’:
plugin_common.c:455:9: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [enabled by default]
plugin_common.c:455:9: note: expected ‘int (**)(void)’ but argument is of type ‘int (**)(void _, int,  const char *, const char *, const char *, const char *_, unsigned int _)’
plugin_common.c: In function ‘_plug_get_realm’:
plugin_common.c:501:9: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [enabled by default]
plugin_common.c:501:9: note: expected ‘int (__)(void)’ but argument is of type ‘int (__)(void *, int,  const char *_, const char *_)’
(cd . && ln -fs plugin_common.lo plugin_common.o)
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -shared xoauth.lo xoauth_init.lo plugin_common.lo -loauth -lcrypt -lresolv -lc -Wl,-soname -Wl,libxoauth.so.2 -o libxoauth.so.2.0.22
/usr/bin/ld: xoauth.lo: relocation R_X86_64_PC32 against symbol `generate_xoauth_token' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *_\* [libxoauth.so.2.0.22] Error 1

**Comment by simmel** [comment]
No idea why I didn't solved this issue a long time ago and I'm sorry for that.

It seems to work now(?):

```
sarena:~/code/saslxoauthᛘmaster$ uname -a
Linux sarena.waza.se 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
sarena:~/code/saslxoauthᛘmaster$ make
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -Wshadow -Wpointer-arith -Wconversion -Wcast-qual -Wwrite-strings -Wunreachable-code -DHAVE_CONFIG_H -I. -O2 -c xoauth.c -fPIC -DPIC -o xoauth.lo
xoauth.c: In function ‘xoauth_client_mech_step’:
xoauth.c:485:21: warning: conversion to ‘unsigned int’ from ‘size_t {aka long unsigned int}’ may alter its value [-Wconversion]
     *clientoutlen = strlen(xoauthstring)+1;
                     ^
(cd . && ln -fs xoauth.lo xoauth.o)
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -Wshadow -Wpointer-arith -Wconversion -Wcast-qual -Wwrite-strings -Wunreachable-code -DHAVE_CONFIG_H -I. -O2 -c xoauth_init.c -fPIC -DPIC -o xoauth_init.lo
(cd . && ln -fs xoauth_init.lo xoauth_init.o)
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -Wshadow -Wpointer-arith -Wconversion -Wcast-qual -Wwrite-strings -Wunreachable-code -DHAVE_CONFIG_H -I. -O2 -c plugin_common.c -fPIC -DPIC -o plugin_common.lo
plugin_common.c: In function ‘sockaddr_unmapped’:
plugin_common.c:99:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     addr = *(uint32_t *)&sin6->sin6_addr.s6_addr[12];
     ^
plugin_common.c: In function ‘_plug_get_simple’:
plugin_common.c:348:47: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [-Wincompatible-pointer-types]
     ret = utils->getcallback(utils->conn, id, &simple_cb, &simple_context);
                                               ^
plugin_common.c:348:47: note: expected ‘int (**)(void)’ but argument is of type ‘int (**)(void *, int,  const char **, unsigned int *)’
plugin_common.c:354:34: warning: conversion to ‘int’ from ‘unsigned int’ may change the sign of the result [-Wsign-conversion]
  ret = simple_cb(simple_context, id, result, NULL);
                                  ^
plugin_common.c: In function ‘_plug_get_password’:
plugin_common.c:410:9: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [-Wincompatible-pointer-types]
         &pass_cb, &pass_context);
         ^
plugin_common.c:410:9: note: expected ‘int (**)(void)’ but argument is of type ‘int (**)(sasl_conn_t *, void *, int,  sasl_secret_t **) {aka int (**)(struct sasl_conn *, void *, int,  struct sasl_secret **)}’
plugin_common.c: In function ‘_plug_challenge_prompt’:
plugin_common.c:456:9: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [-Wincompatible-pointer-types]
         &chalprompt_cb, &chalprompt_context);
         ^
plugin_common.c:456:9: note: expected ‘int (**)(void)’ but argument is of type ‘int (**)(void *, int,  const char *, const char *, const char *, const char **, unsigned int *)’
plugin_common.c:459:42: warning: conversion to ‘int’ from ‘unsigned int’ may change the sign of the result [-Wsign-conversion]
  ret = chalprompt_cb(chalprompt_context, id,
                                          ^
plugin_common.c: In function ‘_plug_get_realm’:
plugin_common.c:502:9: warning: passing argument 3 of ‘utils->getcallback’ from incompatible pointer type [-Wincompatible-pointer-types]
         &realm_cb, &realm_context);
         ^
plugin_common.c:502:9: note: expected ‘int (**)(void)’ but argument is of type ‘int (**)(void *, int,  const char **, const char **)’
plugin_common.c: In function ‘_plug_make_prompts’:
plugin_common.c:546:41: warning: conversion to ‘long unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
     alloc_size = sizeof(sasl_interact_t)*num;
                                         ^
plugin_common.c:547:29: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
     prompts = utils->malloc(alloc_size);
                             ^
plugin_common.c:552:24: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
     memset(prompts, 0, alloc_size);
                        ^
plugin_common.c: In function ‘_plug_parseuser’:
plugin_common.c:749:24: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
  *user = utils->malloc(r - input + 1);
                        ^
plugin_common.c:751:28: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
      strncpy(*user, input, r - input +1);
                            ^
plugin_common.c: In function ‘_plug_snprintf_os_info’:
plugin_common.c:915:21: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
     snprintf(osbuf, osbuf_len, "%s %s", os.sysname, os.release);
                     ^
(cd . && ln -fs plugin_common.lo plugin_common.o)
gcc -Wall -Wextra -pedantic -I/usr/include/sasl -g -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -fPIE --param ssp-buffer-size=1 -Wshadow -Wpointer-arith -Wconversion -Wcast-qual -Wwrite-strings -Wunreachable-code -shared xoauth.lo xoauth_init.lo plugin_common.lo -loauth -lcrypt -lresolv -lc -Wl,-soname -Wl,libxoauth.so.2 -o libxoauth.so.2.0.22
```

Let me know if it still doesn't work for you.
