### ISSUE TITLE
saslxoauth not works with python2.7

### ISSUE THREAD

**Issue by MrDini123** [simmel/saslxoauth#4]
Hi!

I just, found this really cool plugin for mutt. I compiled it on my embedded (2.6.31.8 kernel based) arm device.

But I have python 2.7.10 and 3.5.1 installed only, I haven't got the 2.4 version, which is outdated. So I tried to use the Google oauth2.py script to generate the tokens. I inserted the command to a cronjob, So at every 1 hour, it refreshes the token.

But, it doesn't saves the last token to ~/.xoauthrc... :(

And the saslxoauth not works with this.... Is there any workaround, or way to save the actual token to the .xoauthrc? Or will the module rewritten for the new script?

Thanks for all of Your hard work!

Ps: sorry for my bad English...

**Comment by MrDini123** [comment]
Oh, sorry user error... With @zmugal's script at an another issue ticket, I Can use it. Awesome! :)

**Comment by simmel** [comment]
On Fri, 2016-11-25 at 23:53:35 -0800, MrDini123 wrote:
> Oh, sorry user error... With @zmugal's script at an another issue ticket, I Can use it. Awesome! :)

Exactly what I was going to suggest = )
